/**********************************************************************************
*  File generated by Segger's emUSBD Audio Device Generator tool Version 1.01
*
*  Generated: 2024-05-10 11:26:40
*  from file: speaker_mic_configs.uad
*
**********************************************************************************/

// This configuration models an USB audio 1.0 device containing a speaker and a microphone,
// each connected to an USB endpoint:
//
//   +-------------+       +---------------+       +-------------------+
//   |             |       | Feature Unit  |       |                   |
//   |   Speaker   +<------+               +<------+  USB OUT endpoint |
//   |             |       | Mute / Volume |       |                   |
//   +-------------+       +---------------+       +-------------------+
//
//   +-------------+       +---------------+       +-------------------+
//   |             |       | Feature Unit  |       |                   |
//   | Microphone  +------>+               +------>+  USB IN endpoint  |
//   |             |       | Mute / Volume |       |                   |
//   +-------------+       +---------------+       +-------------------+
//
// The speaker uses two 16-bit channels (stereo) with sample frequencies 16000Hz.
// The microphone has a single 16-bit channel (stereo) with a sample frequencies 16000Hz.


#ifndef USBD_AC_CFG_SPEAKER_MIC_CONFIGS_H_     /* Avoid multiple inclusion */
#define USBD_AC_CFG_SPEAKER_MIC_CONFIGS_H_


#include "USB_AC.h"

#define USBD_AC_AUDIO_VERSION                            1

//
// Control unit / entity IDs
//
#define USBD_AC_ID_CONTROL                         0x00000u
#define USBD_AC_ID_UNIT_USBIn                      0x00100u
#define USBD_AC_ID_UNIT_SpeakerControl             0x00200u
#define USBD_AC_ID_UNIT_Speaker                    0x00300u
#define USBD_AC_ID_UNIT_Microphone                 0x00400u
#define USBD_AC_ID_UNIT_MicControl                 0x00500u
#define USBD_AC_ID_UNIT_USBOut                     0x00600u
#define USBD_AC_ID_AS_Speaker                      0x10000u
#define USBD_AC_ID_EP_Speaker                      0x1ff00u
#define USBD_AC_ID_AS_Microphone                   0x20000u
#define USBD_AC_ID_EP_Microphone                   0x2ff00u

//
// Interfaces
//
#define USBD_AC_INTERFACE_Control                        0u
#define USBD_AC_INTERFACE_Speaker                        1u
#define USBD_AC_INTERFACE_Microphone                     2u

//
// Endpoint indexes
//
#define USBD_AC_DATA_EP_Speaker                          0u
#define USBD_AC_DATA_EP_Microphone                       1u

//
// Configuration for 'speaker_mic_configs'
//
#define USB_AC_CONFIGURATION                     (&USB_AC_Config_speaker_mic_configs)

extern const USBD_AC_CONFIG    USB_AC_Config_speaker_mic_configs;

//
// User defined macros
//
#define SPEAKER_MIC_USB_PRODUCT_ID     0x1301
#define SPEAKER_FREQUENCIES            16000
#define MICROPHONE_FREQUENCIES         16000


#endif /* USBD_AC_CFG_SPEAKER_MIC_CONFIGS_H_ */
